language: go

go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  global:
    - GO111MODULE=on

script:
  - go mod download
  - go mod verify
  - go test ./...
  - go test -race ./...

matrix:
  allow_failures:
    - go: tip
