language: go

go:
  - 1.13.x
  - master

env:
  global:
    - GO111MODULE=on

arch:
  - amd64

os:
  - linux
  - osx
  - windows

script:
  - go mod download
  - go mod verify
  - go test ./...
  - go test -race ./...
  - go build

matrix:
  allow_failures:
    - go: tip
