language: go

go:
  - 1.13.x
  - tip

env:
  global:
    - GO111MODULE=on

arch:
  - amd64
  - arm64

os:
  - linux
  - osx
  - windows

script:
  - go mod download
  - go mod verify
  - go test ./...
  - go test -race ./...

matrix:
  allow_failures:
    - go: tip
